<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDNwxJTF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDNwxJTF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDNwxJTF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDNwxJTF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDNwxJTF\App_KernelDevDebugContainer([
    'container.build_hash' => 'DNwxJTF',
    'container.build_id' => 'ac76651a',
    'container.build_time' => 1725032849,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDNwxJTF');
